# Generated by Django 3.2.10 on 2024-06-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('causes', models.TextField(blank=True, null=True)),
                ('symptoms_features', models.TextField(blank=True, null=True)),
                ('investigations', models.TextField(blank=True, null=True)),
                ('treatments', models.TextField(blank=True, null=True)),
                ('surgical_options', models.TextField(blank=True, null=True)),
                ('preventive_measures', models.TextField(blank=True, null=True)),
                ('emergency_management', models.TextField(blank=True, null=True)),
                ('referral_criteria', models.TextField(blank=True, null=True)),
                ('prognosis', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('further_management', models.TextField(blank=True, null=True)),
                ('referral_criteria', models.TextField(blank=True, null=True)),
                ('conditions', models.ManyToManyField(blank=True, to='users.Condition')),
            ],
        ),
    ]
