# Generated by Django 3.2.10 on 2025-04-08 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20250408_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='condition',
            name='causes',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='description',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='emergency_management',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='investigations',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='preventive_measures',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='prognosis',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='referral_criteria',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='surgical_options',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='symptoms_features',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='treatments',
        ),
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='AttributeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='attribute_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.attribute')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='users.condition'),
        ),
    ]
