# Generated by Django 3.2.10 on 2025-04-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20250408_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributeimage',
            name='caption',
        ),
        migrations.AddField(
            model_name='attributeimage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributeimage',
            name='type',
            field=models.CharField(blank=True, choices=[('TABLE', 'Table'), ('FIGURE', 'Figure')], max_length=255, null=True),
        ),
    ]
