# Generated by Django 3.2.10 on 2025-04-22 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_comment_forumpost_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition_post', to='users.condition'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_post', to='users.department'),
        ),
    ]
