# Generated by Django 3.2.10 on 2025-04-22 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20250422_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_post', to='users.condition'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='department_post', to='users.department'),
            preserve_default=False,
        ),
    ]
