# Generated by Django 3.2.10 on 2025-04-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20250422_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='names',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
