# Generated by Django 3.2.10 on 2025-04-24 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20250422_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptoms',
            name='further_management',
        ),
        migrations.RemoveField(
            model_name='symptoms',
            name='referral_criteria',
        ),
    ]
