# Generated by Django 3.2.10 on 2025-04-25 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20250424_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditions', to='users.department'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(db_index=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='conditions',
            field=models.ManyToManyField(blank=True, related_name='symptoms', to='users.Condition'),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='name',
            field=models.CharField(db_index=True, max_length=250, unique=True),
        ),
    ]
