# Generated by Django 3.2.10 on 2025-05-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20250425_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='symptoms',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, related_name='symptoms', to='users.GroupSymptom'),
        ),
    ]
