# Generated by Django 3.2.10 on 2025-05-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20250503_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptoms',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='symptoms', to='users.GroupSymptom'),
        ),
    ]
